### ISSUE TITLE
Book Errata

### ISSUE THREAD

**Issue by tleyden** [CorticalComputer/Book_NeuroevolutionThroughErlang#1]
Not sure where to put these .. figure a git issue might be a good place.  Let me know if you have a preferred way.
- p136 s/SCH/SHC in paragraph 2.  "whole point of SCH is..."

**Comment by tleyden** [comment]
- p150 s/common/c'mon paragraph 2 "so common, what .."

**Comment by tleyden** [comment]
- P329 paragraph 2: s/reactive/reactivate

**Comment by CorticalComputer** [comment]
Thanks, next edition will have these errors corrected.
