### ISSUE TITLE
Looking up cortex by `cortex` instead of id

### ISSUE THREAD

**Issue by m4ttsch** [CorticalComputer/Book_NeuroevolutionThroughErlang#7]
When you create the ETS table to store the genotype, you add the `{key_pos, 2}` option. 

https://github.com/CorticalComputer/Book_NeuroevolutionThroughErlang/blob/master/Ch_7/genotype.erl#L96

When we look up the cortex from the table at a later point, we pass in `cortex` as the key.

https://github.com/CorticalComputer/Book_NeuroevolutionThroughErlang/blob/master/Ch_7/exoself.erl#L23

However, our lookup fails since our table looks like:

<img width="793" alt="screen shot 2018-03-17 at 8 49 04 pm" src="https://user-images.githubusercontent.com/19544466/37561431-aa194b0e-2a24-11e8-8983-504146916d47.png">

We need to change our cortex lookup to:

```erlang
[Cx] = ets:match_object(Genotype, {cortex, '_', '_', '_', '_'})
```

**Comment by CorticalComputer** [comment]
There are utilizations of key_pos 2 in certain methods that need it, and for certain expansions where Id is utilized.
